import { createHmac, timingSafeEqual } from "node:crypto";
import { EXTERNAL_SOURCES, MEDIA_TYPES, type MediaCandidate } from "./types";
type Payload = { candidate: unknown; expiresAt: number };
const DEFAULT_TTL_MS = 60 * 60 * 1000;
export function encodeCandidateToken(candidate: MediaCandidate, sessionToken: string, now = Date.now(), ttlMs = DEFAULT_TTL_MS) { const payload = Buffer.from(JSON.stringify({ candidate, expiresAt: now + ttlMs } satisfies Payload)).toString("base64url"); return `${payload}.${signature(payload, sessionToken).toString("base64url")}`; }
export function decodeCandidateToken(token: string, sessionToken: string, now = Date.now()): MediaCandidate | null { const [payload, encodedSignature, extra] = token.split("."); if (!payload || !encodedSignature || extra) return null; let provided: Buffer; try { provided = Buffer.from(encodedSignature, "base64url"); } catch { return null; } const expected = signature(payload, sessionToken); if (provided.length !== expected.length || !timingSafeEqual(provided, expected)) return null; let parsed: Payload; try { parsed = JSON.parse(Buffer.from(payload, "base64url").toString("utf8")) as Payload; } catch { return null; } if (!Number.isFinite(parsed.expiresAt) || parsed.expiresAt < now) return null; return parseCandidate(parsed.candidate); }
function signature(payload: string, sessionToken: string) { return createHmac("sha256", sessionToken).update(payload).digest(); }
function parseCandidate(value: unknown): MediaCandidate | null { if (!value || typeof value !== "object") return null; const item = value as Record<string, unknown>; if (!EXTERNAL_SOURCES.includes(item.source as never) || !MEDIA_TYPES.includes(item.type as never)) return null; if (!shortString(item.externalId, 128) || !optionalString(item.externalSubId, 128) || !shortString(item.title, 500)) return null; for (const name of ["originalTitle","romanizedTitle"] as const) if (!optionalString(item[name],500)) return null; for (const name of ["coverUrl","externalUrl"] as const) if (!optionalString(item[name],2_000) || (typeof item[name] === "string" && !httpsUrl(item[name]))) return null; if (!optionalString(item.description,8_000) || !optionalString(item.credit,1_000)) return null; for (const name of ["year", "episodeCount", "pageCount"] as const) if (!optionalNonNegativeNumber(item[name])) return null; const source = item.source as MediaCandidate["source"]; const externalId = item.externalId as string; const externalSubId = typeof item.externalSubId === "string" ? item.externalSubId : ""; return { key: `${source}:${externalId}:${externalSubId}`, type: item.type as MediaCandidate["type"], source, externalId, externalSubId, title: item.title as string, originalTitle: stringOrNull(item.originalTitle), romanizedTitle: stringOrNull(item.romanizedTitle), year: numberOrNull(item.year), episodeCount: numberOrNull(item.episodeCount), pageCount: numberOrNull(item.pageCount), coverUrl: stringOrNull(item.coverUrl), externalUrl: stringOrNull(item.externalUrl), description: stringOrNull(item.description), credit: stringOrNull(item.credit) }; }
function shortString(value: unknown, max: number): value is string { return typeof value === "string" && value.length > 0 && value.length <= max; }
function optionalString(value: unknown, max: number) { return value == null || (typeof value === "string" && value.length <= max); }
function optionalNonNegativeNumber(value: unknown) { return value == null || (typeof value === "number" && Number.isFinite(value) && value >= 0); }
function numberOrNull(value: unknown) { return typeof value === "number" && Number.isFinite(value) ? value : null; }
function stringOrNull(value: unknown) { return typeof value === "string" ? value : null; }
function httpsUrl(value: string) { try { return new URL(value).protocol === "https:"; } catch { return false; } }
