import * as oidc from "openid-client";

const REQUIRED_ENV=["APP_BASE_URL","OIDC_ISSUER_URL","OIDC_CLIENT_ID","OIDC_CLIENT_SECRET","OIDC_ADMIN_ROLE","OIDC_USER_ROLE"] as const;
let cached:{key:string;config:Promise<oidc.Configuration>}|null=null;

export type OidcIdentity={subject:string;email:string;role:"ADMIN"|"USER"};
export function missingOidcConfiguration(){return REQUIRED_ENV.filter(name=>!process.env[name]?.trim());}
export function oidcConfigured(){return missingOidcConfiguration().length===0;}
function env(name:(typeof REQUIRED_ENV)[number]){const value=process.env[name]?.trim();if(!value)throw new Error(`Missing OIDC configuration: ${name}`);return value;}
function redirectUri(){return new URL("/login/oidc/callback",env("APP_BASE_URL")).toString();}
async function configuration(){const issuer=env("OIDC_ISSUER_URL");const clientId=env("OIDC_CLIENT_ID");const secret=env("OIDC_CLIENT_SECRET");const key=`${issuer}\0${clientId}\0${secret}`;if(cached?.key!==key)cached={key,config:oidc.discovery(new URL(issuer),clientId,secret)};return cached.config;}
export async function beginOidcLogin(){const config=await configuration();const codeVerifier=oidc.randomPKCECodeVerifier();const codeChallenge=await oidc.calculatePKCECodeChallenge(codeVerifier);const state=oidc.randomState();const nonce=oidc.randomNonce();const url=oidc.buildAuthorizationUrl(config,{redirect_uri:redirectUri(),scope:"openid email profile",code_challenge:codeChallenge,code_challenge_method:"S256",state,nonce});return{url,codeVerifier,state,nonce};}
export async function completeOidcLogin(currentUrl:URL,transaction:{codeVerifier:string;state:string;nonce:string}){const config=await configuration();const tokens=await oidc.authorizationCodeGrant(config,currentUrl,{pkceCodeVerifier:transaction.codeVerifier,expectedState:transaction.state,expectedNonce:transaction.nonce,idTokenExpected:true});const claims=tokens.claims() as Record<string,unknown>|undefined;if(!claims)throw new Error("OIDC provider did not return identity claims");return parseOidcIdentity(claims);}
export function parseOidcIdentity(claims:Record<string,unknown>):OidcIdentity{const subject=typeof claims.sub==="string"?claims.sub.trim():"";const email=typeof claims.email==="string"?claims.email.trim().toLowerCase():"";if(!subject||!email||claims.email_verified!==true)throw new Error("OIDC identity requires a verified email");const roles=Array.isArray(claims.roles)?claims.roles.filter((value):value is string=>typeof value==="string"):typeof claims.role==="string"?[claims.role]:[];const admin=env("OIDC_ADMIN_ROLE");const user=env("OIDC_USER_ROLE");if(roles.includes(admin))return{subject,email,role:"ADMIN"};if(roles.includes(user))return{subject,email,role:"USER"};throw new Error("OIDC identity is not allowed for media-list");}
