-- Runtime migrations are mirrored in src/db/migrations.ts so the standalone server
-- does not depend on SQL files being present on disk. This file documents the schema.
CREATE TABLE users (id TEXT PRIMARY KEY NOT NULL, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'USER', active INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL);
CREATE TABLE sessions (token_hash TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE invites (id TEXT PRIMARY KEY NOT NULL, token_hash TEXT NOT NULL UNIQUE, created_by TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at INTEGER NOT NULL, used_at INTEGER, created_at INTEGER NOT NULL);
CREATE TABLE media (id TEXT PRIMARY KEY NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, original_title TEXT, country_code TEXT, year INTEGER, external_source TEXT NOT NULL, external_id TEXT NOT NULL, external_sub_id TEXT NOT NULL DEFAULT '', runtime_minutes INTEGER, episode_count INTEGER, page_count INTEGER, cover_url TEXT, metadata_json TEXT, created_at INTEGER NOT NULL, UNIQUE(external_source, external_id, external_sub_id));
CREATE TABLE user_media (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, media_id TEXT NOT NULL REFERENCES media(id) ON DELETE CASCADE, status TEXT NOT NULL DEFAULT 'PLANNED', score INTEGER, progress_current INTEGER NOT NULL DEFAULT 0, progress_total INTEGER, notes TEXT, time_spent_override_minutes INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, UNIQUE(user_id, media_id));
CREATE TABLE import_batches (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, kind TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE import_rows (id TEXT PRIMARY KEY NOT NULL, batch_id TEXT NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE, raw_input TEXT NOT NULL, user_data_json TEXT, candidates_json TEXT NOT NULL DEFAULT '[]', selected_candidate_key TEXT, state TEXT NOT NULL DEFAULT 'PENDING', error_message TEXT, created_at INTEGER NOT NULL);
