import test from "node:test";
import assert from "node:assert/strict";
import { count } from "drizzle-orm";
import { media, userMedia } from "../src/db/schema";
import { authenticate, createAdmin, createInvite, registerWithInvite, setUserPassword } from "../src/lib/services/users";
import { addMediaToUser, deleteUserMediaMany, listUserMedia, updateUserMedia } from "../src/lib/services/media";
import type { MediaCandidate } from "../src/lib/types";
import { parseCsv, stringifyCsv } from "../src/lib/csv";
import { openTestDatabase } from "./db";
const synthetic:MediaCandidate={key:"ANILIST:999001:",type:"ANIME",source:"ANILIST",externalId:"999001",externalSubId:"",title:"Synthetic Anime",originalTitle:"Synthetic Original",countryCode:"JP",year:2026,episodeCount:12};
async function twoUsers(){process.env.MAX_USERS="5";const bundle=openTestDatabase();const admin=await createAdmin(bundle.db,"admin_user","correct-horse-battery");const invite=await createInvite(bundle.db,admin);const user=await registerWithInvite(bundle.db,invite,"second_user","another-good-password");return{...bundle,admin,user};}
test("user-media state is isolated by user id",async()=>{const{db,sqlite,admin,user}=await twoUsers();try{await addMediaToUser(db,admin,synthetic,{status:"COMPLETED",score:9});const adminList=await listUserMedia(db,admin);assert.equal(adminList.length,1);await updateUserMedia(db,user,adminList[0].userMediaId,{status:"DROPPED",score:1,progressCurrent:1,progressTotal:12,notes:"should not apply"});const after=await listUserMedia(db,admin);assert.equal(after[0].status,"COMPLETED");assert.equal(after[0].score,9);assert.equal((await listUserMedia(db,user)).length,0);}finally{sqlite.close();}});
test("focused list updates preserve unrelated state and completed fills known progress",async()=>{const{db,sqlite,admin}=await twoUsers();try{await addMediaToUser(db,admin,synthetic,{status:"IN_PROGRESS",score:8,progressCurrent:4,progressTotal:12,notes:"keep me"});const before=(await listUserMedia(db,admin))[0];await updateUserMedia(db,admin,before.userMediaId,{score:9});const afterScore=(await listUserMedia(db,admin))[0];assert.equal(afterScore.score,9);assert.equal(afterScore.status,"IN_PROGRESS");assert.equal(afterScore.progressCurrent,4);assert.equal(afterScore.progressTotal,12);assert.equal(afterScore.notes,"keep me");await updateUserMedia(db,admin,before.userMediaId,{status:"COMPLETED"});const afterStatus=(await listUserMedia(db,admin))[0];assert.equal(afterStatus.status,"COMPLETED");assert.equal(afterStatus.progressCurrent,12);assert.equal(afterStatus.score,9);assert.equal(afterStatus.notes,"keep me");}finally{sqlite.close();}});
test("completed imported media starts at known total progress",async()=>{const{db,sqlite,admin}=await twoUsers();try{await addMediaToUser(db,admin,synthetic,{status:"COMPLETED"});const item=(await listUserMedia(db,admin))[0];assert.equal(item.progressTotal,12);assert.equal(item.progressCurrent,12);}finally{sqlite.close();}});
test("list filters, sorting, and bulk removal operate on user-owned data",async()=>{const{db,sqlite,admin,user}=await twoUsers();try{const book:MediaCandidate={key:"OPENLIBRARY:OL1W:",type:"BOOK",source:"OPENLIBRARY",externalId:"OL1W",externalSubId:"",title:"Alpha Book",year:2020,pageCount:300};await addMediaToUser(db,admin,synthetic,{score:5});await addMediaToUser(db,admin,book,{score:9,notes:"favorite"});await addMediaToUser(db,user,synthetic,{score:10});const filtered=await listUserMedia(db,admin,{types:["BOOK"],scoreMin:8,hasNotes:true,sort:"title",direction:"asc"});assert.deepEqual(filtered.map(item=>item.title),["Alpha Book"]);const adminRows=await listUserMedia(db,admin);const userRow=(await listUserMedia(db,user))[0];await deleteUserMediaMany(db,admin,[adminRows[0].userMediaId,userRow.userMediaId]);assert.equal((await listUserMedia(db,admin)).length,1);assert.equal((await listUserMedia(db,user)).length,1);}finally{sqlite.close();}});
test("external identity is globally deduplicated while user state stays separate",async()=>{const{db,sqlite,admin,user}=await twoUsers();try{await addMediaToUser(db,admin,synthetic,{score:8});await addMediaToUser(db,user,synthetic,{score:5});const mediaCount=(await db.select({value:count()}).from(media))[0].value;const stateCount=(await db.select({value:count()}).from(userMedia))[0].value;assert.equal(mediaCount,1);assert.equal(stateCount,2);assert.equal((await listUserMedia(db,admin))[0].score,8);assert.equal((await listUserMedia(db,user))[0].score,5);}finally{sqlite.close();}});
test("registration is invite-only, invite is one-time, and MAX_USERS is enforced",async()=>{process.env.MAX_USERS="2";const{db,sqlite}=openTestDatabase();try{const admin=await createAdmin(db,"admin_user","correct-horse-battery");const token=await createInvite(db,admin);await registerWithInvite(db,token,"invited_user","another-good-password");await assert.rejects(()=>registerWithInvite(db,token,"third_user","third-good-password"));await assert.rejects(()=>createInvite(db,admin));}finally{sqlite.close();process.env.MAX_USERS="5";}});
test("password rotation invalidates the old credential",async()=>{const{db,sqlite}=openTestDatabase();try{await createAdmin(db,"admin_user","correct-horse-battery");assert.ok(await authenticate(db,"admin_user","correct-horse-battery"));await setUserPassword(db,"admin_user","new-correct-horse-battery");assert.equal(await authenticate(db,"admin_user","correct-horse-battery"),null);assert.ok(await authenticate(db,"admin_user","new-correct-horse-battery"));}finally{sqlite.close();}});
test("CSV serializer round-trips provider identity and quoted user text",()=>{const rows=[["external_source","external_id","notes"],["TMDB","1396","comma, quote \" and\nnewline"]];const encoded=stringifyCsv(rows);assert.deepEqual(parseCsv(encoded),rows);});
