import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { getDatabase } from "@/db";
import { scheduleMediaEnrichment } from "@/lib/enrichment-runtime";
import { listUserMedia, type MediaSort, type SortDirection } from "@/lib/services/media";
import { externalMediaUrl } from "@/lib/providers/urls";
import { isMediaStatus, isMediaType } from "@/lib/user-media";
import type { MediaStatus } from "@/lib/types";
import { LibrarySettings } from "@/components/library-settings";
import { LibraryTable } from "@/components/library-table";
const statuses:Array<[string,MediaStatus|""]>=[["All",""],["In progress","IN_PROGRESS"],["Completed","COMPLETED"],["On hold","ON_HOLD"],["Dropped","DROPPED"],["Planned","PLANNED"]];const sortKeys=new Set<MediaSort>(["updated","title","score","progress","type","year"]);const defaultColumns=["status","score","progress","type"];
export default async function Home({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const user=await requireUser();scheduleMediaEnrichment();const params=await searchParams;const status=isMediaStatus(params.status)?params.status:undefined;const selectedTypes=(params.types??"").split(",").filter(isMediaType);const q=params.q?.trim()??"";const scoreMin=parseScore(params.scoreMin);const hasNotes=params.hasNotes==="1";const sort=sortKeys.has(params.sort as MediaSort)?params.sort as MediaSort:"updated";const direction:SortDirection=params.dir==="asc"?"asc":"desc";const visibleColumns=parseColumns(params.cols);const items=await listUserMedia(getDatabase().db,user.id,{status,types:selectedTypes,q,scoreMin,hasNotes,sort,direction});const current=queryPath(params);const clearHref=queryPath(status?{status}:{});const sortLinks=Object.fromEntries([...sortKeys].map(key=>[key,{asc:queryPath({...params,sort:key,dir:"asc"}),desc:queryPath({...params,sort:key,dir:"desc"})}])) as Record<MediaSort,Record<SortDirection,string>>;return <section className="libraryPage"><div className="pageTitle libraryTitle"><div><h1>Your media</h1><p className="muted listSummary">{items.length} positions</p></div><Link className="button" href="/media/new">+ Add media</Link></div>{params.error&&<p className="error">{params.error}</p>}<nav className="statusTabs" aria-label="List status">{statuses.map(([label,value])=><Link key={value||"all"} className={(status??"")===value?"active":""} href={queryPath({...params,status:value||undefined})}>{label}</Link>)}</nav><div className="listTools"><form method="get" className="listSearch">{Object.entries(params).filter(([key])=>key!=="q").map(([key,value])=>value?<input key={key} type="hidden" name={key} value={value}/>:null)}<input name="q" defaultValue={q} placeholder="Search your list" aria-label="Search your list"/><button className="secondary" type="submit">Search</button></form><LibrarySettings selectedTypes={selectedTypes} scoreMin={scoreMin} hasNotes={hasNotes} sort={sort} direction={direction} visibleColumns={visibleColumns}/>{hasSecondaryFilters(params)&&<Link className="clearFilter" href={clearHref}>Clear filters</Link>}</div>{items.length?<LibraryTable items={items.map(item=>({...item,externalUrl:externalMediaUrl(item.source,item.externalId,item.externalSubId),updatedAt:item.updatedAt.toISOString()}))} returnTo={current} visibleColumns={visibleColumns} sort={sort} direction={direction} sortLinks={sortLinks}/>:<div className="empty"><p>No positions match these filters.</p><Link href="/media/new">Add a position</Link></div>}</section>}
function parseScore(value?:string){if(!value||!/^\d+$/.test(value))return undefined;const n=Number(value);return n>=1&&n<=10?n:undefined;}function parseColumns(value?:string){if(!value)return defaultColumns;const allowed=new Set(["status","score","progress","type","updated"]);const parsed=value.split(",").filter(item=>allowed.has(item));return parsed.length?parsed:defaultColumns;}function queryPath(values:Record<string,string|undefined>){const p=new URLSearchParams();for(const[key,value]of Object.entries(values)){if(value)p.set(key,value);}const q=p.toString();return q?`/?${q}`:"/";}function hasSecondaryFilters(params:Record<string,string|undefined>){return Boolean(params.q||params.types||params.scoreMin||params.hasNotes||params.sort||params.dir||params.cols);}
