"use client";
import { useRef } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import type { MediaType } from "@/lib/types";
import type { MediaSort, SortDirection } from "@/lib/services/media";

const types: Array<[MediaType,string]> = [["ANIME","Anime"],["MOVIE","Movies"],["SERIES","Series"],["BOOK","Books"],["GAME","Games"]];
const columns = [["status","Status"],["score","Score"],["progress","Progress"],["type","Type"],["updated","Updated"]] as const;
export function LibrarySettings({ selectedTypes, scoreMin, hasNotes, sort, direction, visibleColumns }: { selectedTypes: MediaType[]; scoreMin?: number; hasNotes: boolean; sort: MediaSort; direction: SortDirection; visibleColumns: string[] }) { const dialog = useRef<HTMLDialogElement>(null); const router = useRouter(); const searchParams = useSearchParams(); function apply(form: HTMLFormElement) { const data = new FormData(form); const params = new URLSearchParams(searchParams.toString()); params.delete("types"); params.delete("scoreMin"); params.delete("hasNotes"); params.delete("sort"); params.delete("dir"); params.delete("cols"); const chosenTypes = data.getAll("type").map(String); if (chosenTypes.length) params.set("types", chosenTypes.join(",")); const min = String(data.get("scoreMin") ?? ""); if (min) params.set("scoreMin", min); if (data.get("hasNotes")) params.set("hasNotes", "1"); const nextSort = String(data.get("sort") ?? "updated"); const nextDir = String(data.get("dir") ?? "desc"); if (nextSort !== "updated") params.set("sort", nextSort); if (nextDir !== "desc") params.set("dir", nextDir); const selectedColumns = data.getAll("column").map(String); if (selectedColumns.length) params.set("cols", selectedColumns.join(",")); router.push(params.toString() ? `/?${params}` : "/"); dialog.current?.close(); }
return <><button type="button" className="secondary settingsButton" onClick={() => dialog.current?.showModal()}>Settings</button><dialog className="settingsDialog" ref={dialog}><form onSubmit={(event) => { event.preventDefault(); apply(event.currentTarget); }}><div className="dialogHeading"><div><h2>List settings</h2><p className="muted">Filter, sort, and choose the columns you need.</p></div><button className="iconButton secondary" type="button" onClick={() => dialog.current?.close()} aria-label="Close">×</button></div><fieldset><legend>Media types</legend><div className="choiceGrid">{types.map(([value,label]) => <label className="checkChoice" key={value}><input type="checkbox" name="type" value={value} defaultChecked={selectedTypes.includes(value)}/>{label}</label>)}</div></fieldset><div className="settingsGrid"><label>Minimum score<select name="scoreMin" defaultValue={scoreMin ?? ""}><option value="">Any</option>{Array.from({length:10},(_,i)=>i+1).map(value=><option value={value} key={value}>{value}+</option>)}</select></label><label>Sort by<select name="sort" defaultValue={sort}><option value="updated">Last updated</option><option value="title">Title</option><option value="score">Score</option><option value="progress">Progress</option><option value="type">Type</option><option value="year">Year</option></select></label><label>Direction<select name="dir" defaultValue={direction}><option value="desc">Descending</option><option value="asc">Ascending</option></select></label><label className="checkChoice inlineChoice"><input type="checkbox" name="hasNotes" defaultChecked={hasNotes}/>Only items with notes</label></div><fieldset><legend>Visible columns</legend><div className="choiceGrid">{columns.map(([value,label]) => <label className="checkChoice" key={value}><input type="checkbox" name="column" value={value} defaultChecked={visibleColumns.includes(value)}/>{label}</label>)}</div></fieldset><div className="dialogActions"><button className="secondary" type="button" onClick={() => dialog.current?.close()}>Cancel</button><button type="submit">Apply</button></div></form></dialog></>; }
