"use client";
import { useRef } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import type { MediaType } from "@/lib/types";
import type { MediaSort, SortDirection } from "@/lib/services/media";
import { DEFAULT_LIBRARY_DIRECTION, DEFAULT_LIBRARY_SORT, DEFAULT_VISIBLE_COLUMNS, serializeVisibleColumns } from "@/lib/library-view";
const types:Array<[MediaType,string]>=[["ANIME","Anime"],["MOVIE","Movies"],["SERIES","Series"],["BOOK","Books"],["GAME","Games"]];const columns=[["status","Status"],["score","Score"],["progress","Progress"],["type","Type"],["added","Date added"],["updated","Date updated"]]as const;
export function LibrarySettings({selectedTypes,scoreMin,hasNotes,sort,direction,visibleColumns}:{selectedTypes:MediaType[];scoreMin?:number;hasNotes:boolean;sort:MediaSort;direction:SortDirection;visibleColumns:string[]}){const dialog=useRef<HTMLDialogElement>(null);const formRef=useRef<HTMLFormElement>(null);const router=useRouter();const searchParams=useSearchParams();const effectiveTypes=selectedTypes.length?selectedTypes:types.map(([value])=>value);function apply(form:HTMLFormElement){const data=new FormData(form);const params=new URLSearchParams(searchParams.toString());for(const key of["types","scoreMin","hasNotes","sort","dir","cols"])params.delete(key);const chosenTypes=data.getAll("type").map(String);if(chosenTypes.length>0&&chosenTypes.length<types.length)params.set("types",chosenTypes.join(","));const min=String(data.get("scoreMin")??"");if(min)params.set("scoreMin",min);if(data.get("hasNotes"))params.set("hasNotes","1");const nextSort=String(data.get("sort")??DEFAULT_LIBRARY_SORT);const nextDir=String(data.get("dir")??DEFAULT_LIBRARY_DIRECTION);if(nextSort!==DEFAULT_LIBRARY_SORT)params.set("sort",nextSort);if(nextDir!==DEFAULT_LIBRARY_DIRECTION)params.set("dir",nextDir);const serialized=serializeVisibleColumns(data.getAll("column").map(String));if(serialized)params.set("cols",serialized);router.push(params.toString()?`/?${params}`:"/");dialog.current?.close();}function setChecks(name:string,values:readonly string[]){const form=formRef.current;if(!form)return;for(const input of form.querySelectorAll<HTMLInputElement>(`input[name="${name}"]`))input.checked=values.includes(input.value);}
return <><button type="button" className="secondary settingsButton" onClick={()=>dialog.current?.showModal()}>Settings</button><dialog className="settingsDialog" ref={dialog} aria-labelledby="list-settings-title"><form ref={formRef} onSubmit={event=>{event.preventDefault();apply(event.currentTarget);}}><div className="dialogHeading"><div><h2 id="list-settings-title">List settings</h2><p className="muted">Filter, sort, and choose the columns you need.</p></div><button className="iconButton secondary" type="button" onClick={()=>dialog.current?.close()} aria-label="Close">×</button></div><fieldset><legend>Media types <button className="textAction legendAction" type="button" onClick={()=>setChecks("type",types.map(([value])=>value))}>Reset to all</button></legend><div className="choiceGrid">{types.map(([value,label])=><label className="checkChoice" key={value}><input type="checkbox" name="type" value={value} defaultChecked={effectiveTypes.includes(value)}/>{label}</label>)}</div></fieldset><div className="settingsGrid"><label>Minimum score<select name="scoreMin" defaultValue={scoreMin??""}><option value="">Any</option>{Array.from({length:10},(_,i)=>i+1).map(value=><option value={value} key={value}>{value}+</option>)}</select></label><label>Sort by<select name="sort" defaultValue={sort}><option value="updated">Date updated</option><option value="created">Date added</option><option value="title">Title</option><option value="score">Score</option><option value="progress">Progress</option><option value="type">Type</option><option value="year">Year</option></select></label><label>Direction<select name="dir" defaultValue={direction}><option value="desc">Descending</option><option value="asc">Ascending</option></select></label><label className="checkChoice inlineChoice"><input type="checkbox" name="hasNotes" defaultChecked={hasNotes}/>Only items with notes</label></div><fieldset><legend>Visible columns <button className="textAction legendAction" type="button" onClick={()=>setChecks("column",DEFAULT_VISIBLE_COLUMNS)}>Reset to default</button></legend><div className="choiceGrid">{columns.map(([value,label])=><label className="checkChoice" key={value}><input type="checkbox" name="column" value={value} defaultChecked={visibleColumns.includes(value)}/>{label}</label>)}</div></fieldset><div className="dialogActions"><button className="secondary" type="button" onClick={()=>dialog.current?.close()}>Cancel</button><button type="submit">Apply</button></div></form></dialog></>;}
