import { randomUUID } from "node:crypto";
import { and, eq } from "drizzle-orm";
import type { AppDb } from "@/db";
import { importBatches, importRows } from "@/db/schema";
import { parseCsv, rowsToObjects } from "../csv";
import { parseCandidateKey, resolveExact, resolveExternalUrl, searchAllProviders } from "../providers";
import type { ImportedUserData, MediaCandidate, MediaStatus, MediaType } from "../types";
import { addMediaToUser } from "./media";
export async function createQuickImport(db: AppDb, userId: string, text: string) { const lines = text.split(/\r?\n/).map((x) => x.trim()).filter(Boolean).slice(0, 50); if (!lines.length) throw new Error("Paste at least one title or provider URL"); return createBatch(db, userId, "QUICK", lines.map((line) => ({ raw: line, userData: {} }))); }
export async function createMigrationImport(db: AppDb, userId: string, csv: string) { const objects = rowsToObjects(parseCsv(csv)).slice(0, 100); if (!objects.length) throw new Error("Migration CSV is empty"); const items = objects.map((row, index) => { const raw = (row.source_url || row.title || "").trim(); if (!raw) throw new Error(`row ${index + 2}: source_url or title is required`); return { raw, userData: migrationUserData(row), typeHint: migrationType(row.type) }; }); return createBatch(db, userId, "MIGRATION", items); }
async function createBatch(db: AppDb, userId: string, kind: "QUICK" | "MIGRATION", items: Array<{ raw: string; userData: ImportedUserData; typeHint?: MediaType }>) { const batchId = randomUUID(); await db.insert(importBatches).values({ id: batchId, userId, kind, createdAt: new Date() }); const resolved = await mapLimited(items, 3, async (item) => { try { const found = /^https?:\/\//i.test(item.raw) ? await resolveExternalUrl(item.raw) : await searchAllProviders(item.raw); const candidates = item.typeHint ? found.filter((candidate) => candidate.type === item.typeHint) : found; return { item, candidates, error: null }; } catch (error) { return { item, candidates: [] as MediaCandidate[], error: error instanceof Error ? error.message : "resolver failed" }; } }); await db.insert(importRows).values(resolved.map((result) => ({ id: randomUUID(), batchId, rawInput: result.item.raw, userDataJson: JSON.stringify(result.item.userData), candidatesJson: JSON.stringify(result.candidates), state: result.error ? "ERROR" : "PENDING", errorMessage: result.error, createdAt: new Date() }))); return batchId; }
export async function getBatch(db: AppDb, userId: string, batchId: string) { const batch = (await db.select().from(importBatches).where(and(eq(importBatches.id, batchId), eq(importBatches.userId, userId))).limit(1))[0]; if (!batch) return null; const rows = await db.select().from(importRows).where(eq(importRows.batchId, batchId)); return { batch, rows: rows.map((row) => ({ ...row, candidates: safeJson<MediaCandidate[]>(row.candidatesJson, []), userData: safeJson<ImportedUserData>(row.userDataJson, {}) })) }; }
export async function confirmBatch(db: AppDb, userId: string, batchId: string, selections: Record<string, string>) { const data = await getBatch(db, userId, batchId); if (!data) throw new Error("Import batch not found"); const report = { imported: 0, skipped: 0, invalid: 0 }; for (const row of data.rows) { const selected = selections[row.id]; if (!selected) { report.skipped += 1; await db.update(importRows).set({ state: "SKIPPED" }).where(eq(importRows.id, row.id)); continue; } const parsed = parseCandidateKey(selected); const preview = row.candidates.find((c) => c.key === selected); if (!parsed || !preview) { report.invalid += 1; await db.update(importRows).set({ state: "ERROR", errorMessage: "Selected candidate was not in staging data" }).where(eq(importRows.id, row.id)); continue; } const exact = await resolveExact(parsed.source, parsed.externalId, parsed.externalSubId, preview.type); if (!exact) { report.invalid += 1; await db.update(importRows).set({ state: "ERROR", errorMessage: "Provider validation failed" }).where(eq(importRows.id, row.id)); continue; } const result = await addMediaToUser(db, userId, exact, row.userData); await db.update(importRows).set({ state: "CONFIRMED", selectedCandidateKey: selected, errorMessage: null }).where(eq(importRows.id, row.id)); if (result.inserted) report.imported += 1; else report.skipped += 1; } return report; }
function migrationType(value?: string): MediaType | undefined { if (!value?.trim()) return undefined; const normalized = value.trim().toUpperCase(); if (["ANIME", "MOVIE", "SERIES", "BOOK"].includes(normalized)) return normalized as MediaType; throw new Error(`invalid type ${value}`); }
function migrationUserData(row: Record<string, string>): ImportedUserData { const status = row.status as MediaStatus | undefined; const allowed = new Set(["PLANNED", "IN_PROGRESS", "COMPLETED", "ON_HOLD", "DROPPED"]); if (status && !allowed.has(status)) throw new Error(`invalid status ${status}`); return { status, score: numberOrNull(row.score, 10), progressCurrent: numberOrNull(row.progress_current) ?? 0, progressTotal: numberOrNull(row.progress_total), notes: row.notes || null, timeSpentOverrideMinutes: numberOrNull(row.time_spent_override_minutes) }; }
function numberOrNull(value?: string, max?: number) { if (!value?.trim()) return null; const n = Number.parseInt(value, 10); if (!Number.isInteger(n) || n < 0 || (max != null && n > max)) throw new Error(`invalid number ${value}`); return n; }
function safeJson<T>(value: string | null, fallback: T): T { if (!value) return fallback; try { return JSON.parse(value) as T; } catch { return fallback; } }
async function mapLimited<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>): Promise<R[]> { const output = new Array<R>(items.length); let next = 0; async function worker() { while (true) { const index = next++; if (index >= items.length) return; output[index] = await fn(items[index]); } } await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker)); return output; }
