import { randomUUID } from "node:crypto";
import { and, asc, desc, eq, gte, inArray, isNotNull, like, ne, type SQL } from "drizzle-orm";
import type { AppDb } from "@/db";
import { media, userMedia } from "@/db/schema";
import { resolveExact } from "../providers";
import type { ImportedUserData, MediaCandidate, MediaIdentity, MediaStatus, MediaType } from "../types";
export type MediaSort="created"|"title"|"score"|"progress"|"type"|"year";export type SortDirection="asc"|"desc";export type ListUserMediaFilters={status?:MediaStatus;types?:MediaType[];q?:string;scoreMin?:number;hasNotes?:boolean;sort?:MediaSort;direction?:SortDirection};
export async function ensureMedia(db:AppDb,candidate:MediaCandidate){const existing=await findMedia(db,candidate.source,candidate.externalId,candidate.externalSubId);if(existing){if(existing.metadataStatus!=="READY"){await refreshMediaMetadata(db,existing.id,candidate);return(await findMedia(db,candidate.source,candidate.externalId,candidate.externalSubId))!;}return existing;}await db.insert(media).values({id:randomUUID(),type:candidate.type,externalSource:candidate.source,externalId:candidate.externalId,externalSubId:candidate.externalSubId,...candidateMetadataValues(candidate),metadataStatus:"READY",metadataError:null,metadataRefreshedAt:new Date()}).onConflictDoNothing();const resolved=await findMedia(db,candidate.source,candidate.externalId,candidate.externalSubId);if(!resolved)throw new Error("Failed to create media record");return resolved;}
export async function refreshMediaMetadata(db:AppDb,mediaId:string,candidate:MediaCandidate,refreshedAt=new Date()){await db.update(media).set({...candidateMetadataValues(candidate),metadataStatus:"READY",metadataError:null,metadataRefreshedAt:refreshedAt}).where(eq(media.id,mediaId));}
export async function resolveAndAddMedia(db:AppDb,userId:string,identity:MediaIdentity,userData:ImportedUserData={}){const candidate=await resolveExact(identity.source,identity.externalId,identity.externalSubId,identity.type);if(!candidate)throw new Error("Provider validation failed");assertSameIdentity(candidate,identity);return addMediaToUser(db,userId,candidate,userData);}
export async function addSelectedMediaToUser(db:AppDb,userId:string,candidate:MediaCandidate,userData:ImportedUserData={}){let item=await findMedia(db,candidate.source,candidate.externalId,candidate.externalSubId);if(!item){await db.insert(media).values({id:randomUUID(),type:candidate.type,externalSource:candidate.source,externalId:candidate.externalId,externalSubId:candidate.externalSubId,...candidateMetadataValues(candidate),metadataStatus:"PENDING",metadataError:null,metadataRefreshedAt:null}).onConflictDoNothing();item=await findMedia(db,candidate.source,candidate.externalId,candidate.externalSubId);}else if(item.metadataStatus!=="READY"){await db.update(media).set({...candidateMetadataValues(candidate),type:candidate.type,metadataStatus:"PENDING",metadataError:null}).where(eq(media.id,item.id));item=await findMedia(db,candidate.source,candidate.externalId,candidate.externalSubId);}if(!item)throw new Error("Failed to create media record");const result=await addUserMediaLink(db,userId,item.id,candidate,userData);return{...result,item,needsEnrichment:item.metadataStatus!=="READY"};}
export async function addMediaToUser(db:AppDb,userId:string,candidate:MediaCandidate,userData:ImportedUserData={}){const item=await ensureMedia(db,candidate);const result=await addUserMediaLink(db,userId,item.id,candidate,userData);return{item,...result};}
export async function retryMediaMetadata(db:AppDb,userId:string,mediaId:string){const owned=(await db.select({id:userMedia.id}).from(userMedia).where(and(eq(userMedia.userId,userId),eq(userMedia.mediaId,mediaId))).limit(1))[0];if(!owned)return false;await db.update(media).set({metadataStatus:"PENDING",metadataError:null}).where(eq(media.id,mediaId));return true;}
type UserMediaUpdate={status:MediaStatus;score:number|null;progressCurrent:number;progressTotal:number|null;notes:string|null};
export async function updateUserMedia(db:AppDb,userId:string,id:string,values:Partial<UserMediaUpdate>){if(!Object.keys(values).length)return;const normalized:Partial<UserMediaUpdate>={...values};if(values.status==="COMPLETED"){const current=(await db.select({progressTotal:userMedia.progressTotal}).from(userMedia).where(and(eq(userMedia.id,id),eq(userMedia.userId,userId))).limit(1))[0];const total=values.progressTotal??current?.progressTotal??null;if(total!=null){normalized.progressTotal=total;normalized.progressCurrent=total;}}await db.update(userMedia).set(normalized).where(and(eq(userMedia.id,id),eq(userMedia.userId,userId)));}
export async function deleteUserMedia(db:AppDb,userId:string,id:string){await deleteUserMediaMany(db,userId,[id]);}export async function deleteUserMediaMany(db:AppDb,userId:string,ids:string[]){const unique=[...new Set(ids.filter(Boolean))].slice(0,500);if(!unique.length)return;await db.delete(userMedia).where(and(eq(userMedia.userId,userId),inArray(userMedia.id,unique)));}
export async function listUserMedia(db:AppDb,userId:string,filters:ListUserMediaFilters={}){const clauses:SQL[]=[eq(userMedia.userId,userId)];if(filters.status)clauses.push(eq(userMedia.status,filters.status));if(filters.types?.length)clauses.push(inArray(media.type,filters.types));if(filters.q?.trim())clauses.push(like(media.title,`%${filters.q.trim()}%`));if(filters.scoreMin!=null)clauses.push(gte(userMedia.score,filters.scoreMin));if(filters.hasNotes)clauses.push(and(isNotNull(userMedia.notes),ne(userMedia.notes,""))!);const direction=filters.direction==="asc"?asc:desc;const order=filters.sort==="title"?direction(media.title):filters.sort==="score"?direction(userMedia.score):filters.sort==="progress"?direction(userMedia.progressCurrent):filters.sort==="type"?direction(media.type):filters.sort==="year"?direction(media.year):direction(userMedia.createdAt);return db.select({userMediaId:userMedia.id,mediaId:media.id,title:media.title,originalTitle:media.originalTitle,romanizedTitle:media.romanizedTitle,type:media.type,year:media.year,source:media.externalSource,externalId:media.externalId,externalSubId:media.externalSubId,externalUrl:media.externalUrl,coverUrl:media.coverUrl,metadataStatus:media.metadataStatus,metadataError:media.metadataError,status:userMedia.status,score:userMedia.score,progressCurrent:userMedia.progressCurrent,progressTotal:userMedia.progressTotal,notes:userMedia.notes,createdAt:userMedia.createdAt}).from(userMedia).innerJoin(media,eq(userMedia.mediaId,media.id)).where(and(...clauses)).orderBy(order);}
function candidateMetadataValues(candidate:MediaCandidate){return{title:candidate.title,originalTitle:candidate.originalTitle??null,romanizedTitle:candidate.romanizedTitle??null,year:candidate.year??null,externalUrl:candidate.externalUrl??null,coverUrl:candidate.coverUrl??null};}
async function addUserMediaLink(db:AppDb,userId:string,mediaId:string,candidate:MediaCandidate,userData:ImportedUserData){const existing=(await db.select({id:userMedia.id}).from(userMedia).where(and(eq(userMedia.userId,userId),eq(userMedia.mediaId,mediaId))).limit(1))[0];if(existing)return{inserted:false};const now=new Date();const total=userData.progressTotal??defaultProgressTotal(candidate);const current=userData.status==="COMPLETED"&&total!=null?total:(userData.progressCurrent??0);await db.insert(userMedia).values({id:randomUUID(),userId,mediaId,status:userData.status??"PLANNED",score:userData.score??null,progressCurrent:current,progressTotal:total,notes:userData.notes??null,createdAt:now}).onConflictDoNothing();return{inserted:true};}
export async function findMediaById(db:AppDb,mediaId:string){return(await db.select().from(media).where(eq(media.id,mediaId)).limit(1))[0]??null;}
function assertSameIdentity(candidate:MediaCandidate,identity:MediaIdentity){if(candidate.source!==identity.source||candidate.externalId!==identity.externalId||candidate.externalSubId!==identity.externalSubId)throw new Error("Provider returned a different media identity");if(candidate.type!==identity.type)throw new Error(`Provider item type is ${candidate.type}, expected ${identity.type}`);}
async function findMedia(db:AppDb,source:MediaCandidate["source"],externalId:string,externalSubId:string){return(await db.select().from(media).where(and(eq(media.externalSource,source),eq(media.externalId,externalId),eq(media.externalSubId,externalSubId))).limit(1))[0]??null;}
function defaultProgressTotal(candidate:MediaCandidate){if(candidate.type==="MOVIE")return 1;if(candidate.type==="BOOK")return candidate.pageCount??null;return candidate.episodeCount??null;}
