import { randomUUID } from "node:crypto";import { and,count,eq,gt,isNull } from "drizzle-orm";import type { AppDb } from "@/db";import { invites,passwordResets,sessions,users } from "@/db/schema";import { hashPassword,hashToken,randomToken,verifyPassword } from "../crypto";import { maxUsers } from "../env";
export async function createAdmin(db:AppDb,username:string,password:string){validateCredentials(username,password);const existing=await db.select({value:count()}).from(users);if((existing[0]?.value??0)>0)throw new Error("Database already has users; create further users via invites");const id=randomUUID();await db.insert(users).values({id,username:username.trim(),passwordHash:hashPassword(password),role:"ADMIN",active:true,createdAt:new Date()});return id;}
export async function authenticate(db:AppDb,username:string,password:string){const row=(await db.select().from(users).where(eq(users.username,username.trim())).limit(1))[0];if(!row||!row.active||!verifyPassword(password,row.passwordHash))return null;return row;}
export async function createInvite(db:AppDb,adminId:string,ttlHours=72){const userCount=(await db.select({value:count()}).from(users))[0]?.value??0;if(userCount>=maxUsers())throw new Error(`User limit (${maxUsers()}) reached`);const token=randomToken();await db.insert(invites).values({id:randomUUID(),tokenHash:hashToken(token),createdBy:adminId,createdAt:new Date(),expiresAt:new Date(Date.now()+ttlHours*3_600_000)});return token;}
export async function registerWithInvite(db:AppDb,token:string,username:string,password:string){validateCredentials(username,password);const now=new Date();const invite=(await db.select().from(invites).where(and(eq(invites.tokenHash,hashToken(token)),isNull(invites.usedAt),gt(invites.expiresAt,now))).limit(1))[0];if(!invite)throw new Error("Invite is invalid, expired, or already used");const userCount=(await db.select({value:count()}).from(users))[0]?.value??0;if(userCount>=maxUsers())throw new Error(`User limit (${maxUsers()}) reached`);const id=randomUUID();db.transaction(tx=>{tx.insert(users).values({id,username:username.trim(),passwordHash:hashPassword(password),role:"USER",active:true,createdAt:now}).run();tx.update(invites).set({usedAt:now}).where(eq(invites.id,invite.id)).run();});return id;}
export async function createPasswordReset(db:AppDb,userId:string,createdBy:string|null=null,ttlHours=1,now=new Date()){const user=(await db.select({id:users.id,active:users.active}).from(users).where(eq(users.id,userId)).limit(1))[0];if(!user||!user.active)throw new Error("User is not active");const token=randomToken();await db.delete(passwordResets).where(and(eq(passwordResets.userId,userId),isNull(passwordResets.usedAt)));await db.insert(passwordResets).values({id:randomUUID(),tokenHash:hashToken(token),userId,createdBy,createdAt:now,expiresAt:new Date(now.getTime()+Math.max(1,ttlHours)*3_600_000)});return token;}
export async function createPasswordResetForUsername(db:AppDb,username:string,ttlHours=1){const user=(await db.select({id:users.id}).from(users).where(eq(users.username,username.trim())).limit(1))[0];if(!user)throw new Error(`User '${username.trim()}' not found`);return createPasswordReset(db,user.id,null,ttlHours);}
export async function resetPasswordWithToken(db:AppDb,token:string,password:string,now=new Date()){validatePassword(password);const reset=(await db.select().from(passwordResets).where(and(eq(passwordResets.tokenHash,hashToken(token)),isNull(passwordResets.usedAt),gt(passwordResets.expiresAt,now))).limit(1))[0];if(!reset)throw new Error("Reset link is invalid, expired, or already used");const user=(await db.select({id:users.id,active:users.active}).from(users).where(eq(users.id,reset.userId)).limit(1))[0];if(!user||!user.active)throw new Error("User is not active");db.transaction(tx=>{tx.update(users).set({passwordHash:hashPassword(password)}).where(eq(users.id,user.id)).run();tx.delete(sessions).where(eq(sessions.userId,user.id)).run();tx.update(passwordResets).set({usedAt:now}).where(and(eq(passwordResets.userId,user.id),isNull(passwordResets.usedAt))).run();});return user.id;}
export async function setUserActive(db:AppDb,userId:string,active:boolean){await db.update(users).set({active}).where(eq(users.id,userId));if(!active)await db.delete(sessions).where(eq(sessions.userId,userId));}
export async function setUserPassword(db:AppDb,username:string,password:string){validatePassword(password);const clean=username.trim();const user=(await db.select({id:users.id}).from(users).where(eq(users.username,clean)).limit(1))[0];if(!user)throw new Error(`User '${clean}' not found`);await db.update(users).set({passwordHash:hashPassword(password)}).where(eq(users.id,user.id));await db.delete(sessions).where(eq(sessions.userId,user.id));}
export async function listUsers(db:AppDb){return db.select({id:users.id,username:users.username,role:users.role,active:users.active,createdAt:users.createdAt}).from(users);}
function validateCredentials(username:string,password:string){const clean=username.trim();if(!/^[A-Za-z0-9_.-]{3,32}$/.test(clean))throw new Error("Username must be 3-32 characters: letters, numbers, _, . or -");validatePassword(password);}function validatePassword(password:string){if(password.length<10)throw new Error("Password must be at least 10 characters");}
