import { randomUUID } from "node:crypto";
import { and, count, eq, gt, isNull } from "drizzle-orm";
import type { AppDb } from "@/db";
import { invites, sessions, users } from "@/db/schema";
import { hashPassword, hashToken, randomToken, verifyPassword } from "../crypto";
import { maxUsers } from "../env";
export async function createAdmin(db: AppDb, username: string, password: string) { validateCredentials(username, password); const existing = await db.select({ value: count() }).from(users); if ((existing[0]?.value ?? 0) > 0) throw new Error("Database already has users; create further users via invites"); const id = randomUUID(); await db.insert(users).values({ id, username: username.trim(), passwordHash: hashPassword(password), role: "ADMIN", active: true, createdAt: new Date() }); return id; }
export async function authenticate(db: AppDb, username: string, password: string) { const row = (await db.select().from(users).where(eq(users.username, username.trim())).limit(1))[0]; if (!row || !row.active || !verifyPassword(password, row.passwordHash)) return null; return row; }
export async function createInvite(db: AppDb, adminId: string, ttlHours = 72) { const userCount = (await db.select({ value: count() }).from(users))[0]?.value ?? 0; if (userCount >= maxUsers()) throw new Error(`User limit (${maxUsers()}) reached`); const token = randomToken(); await db.insert(invites).values({ id: randomUUID(), tokenHash: hashToken(token), createdBy: adminId, createdAt: new Date(), expiresAt: new Date(Date.now() + ttlHours * 3_600_000) }); return token; }
export async function registerWithInvite(db: AppDb, token: string, username: string, password: string) { validateCredentials(username, password); const now = new Date(); const invite = (await db.select().from(invites).where(and(eq(invites.tokenHash, hashToken(token)), isNull(invites.usedAt), gt(invites.expiresAt, now))).limit(1))[0]; if (!invite) throw new Error("Invite is invalid, expired, or already used"); const userCount = (await db.select({ value: count() }).from(users))[0]?.value ?? 0; if (userCount >= maxUsers()) throw new Error(`User limit (${maxUsers()}) reached`); const id = randomUUID(); db.transaction((tx) => { tx.insert(users).values({ id, username: username.trim(), passwordHash: hashPassword(password), role: "USER", active: true, createdAt: now }).run(); tx.update(invites).set({ usedAt: now }).where(eq(invites.id, invite.id)).run(); }); return id; }
export async function setUserActive(db: AppDb, userId: string, active: boolean) { await db.update(users).set({ active }).where(eq(users.id, userId)); if (!active) await db.delete(sessions).where(eq(sessions.userId, userId)); }
export async function listUsers(db: AppDb) { return db.select({ id: users.id, username: users.username, role: users.role, active: users.active, createdAt: users.createdAt }).from(users); }
function validateCredentials(username: string, password: string) { const clean = username.trim(); if (!/^[A-Za-z0-9_.-]{3,32}$/.test(clean)) throw new Error("Username must be 3-32 characters: letters, numbers, _, . or -"); if (password.length < 10) throw new Error("Password must be at least 10 characters"); }
